# Generated by Django 5.1.3 on 2024-11-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
