# Generated by Django 5.1.3 on 2024-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_userproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
