# Generated by Django 5.1.3 on 2024-11-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_producthome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthome',
            name='product_name',
            field=models.CharField(max_length=300),
        ),
    ]
