# Generated by Django 5.1.3 on 2024-11-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_producthome_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthome',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
