# Generated by Django 5.1.3 on 2024-11-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_producthome_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthome',
            name='product_id',
        ),
    ]
