# Generated by Django 5.1.3 on 2024-11-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_producthome_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthome',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
