# Generated by Django 5.1.3 on 2024-11-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_producthome_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthome',
            name='product_id',
        ),
    ]
