# Generated by Django 5.1.3 on 2024-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_delete_orders_delete_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
